apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
commonLabels:
  app: example-express-app
  app.kubernetes.io/instance: example-express-app-instance
  app.kubernetes.io/name: example-express-app